lidar:
  lidar_topic: /ptah/lidar_points
  frame_id: ptah/ouster_link

camera:
  image_topic: /ptah/forward/infra1/image_rect_raw/compressed
  projected_topic: /ros2_camera_lidar_fusion/lidar_proj_imgz
  is_compressed: True
  image_size:
    width: 640
    height: 480
  frame_id: ptah/forward_infra1_optical_frame

chessboard:
  pattern_size:
    rows: 8
    columns: 11
  square_size_meters: 0.41

general:
  ros_ws_name: ros2_test_ws
  config_folder: ros2_camera_lidar_fusion/config
  data_folder: ros2_camera_lidar_fusion/data
  correspondence_file: ros2_camera_lidar_fusion_correspondences.txt
  camera_intrinsic_calibration: ptah_camera_intrinsic.yaml
  camera_extrinsic_calibration: ptah_camera_lidar_extrinsic.yaml
  slop: 0.1
  max_file_saved: 100
  keyboard_listener: True
  get_intrinsics: True
  get_extrinsics: True