T_lidar_to_cam:
- - 0.033042467839889705
  - 0.9993956452638069
  - -0.01079534838664914
  - -0.07107704057080719
- - -0.9668333889877145
  - 0.03469918508996529
  - 0.2530398476379224
  - 1.2363951770429404
- - 0.25326151159933585
  - 0.002076242238180398
  - 0.9673956253573757
  - -1.5391117963331404
- - 0.0
  - 0.0
  - 0.0
  - 1.0
